### ISSUE TITLE
Alignment Process Fails

### ISSUE THREAD

**Issue by braincoded** [pietrop/subtitlesComposer-app#1]
I use the sample "Sonnet" from the original Aeneas project, however, other language samples and formats lead to the same situation: The attempt of aligning a text to an audio file just gets always stuck. The button changes to "processing ", that's it.

Aeneas was already installed on the Mac, but I also installed it again using the linked DMG.

Are there any suggestions how to find out what could cause the alignment process to always fail? THX!

**Comment by pietrop** [comment]
Ok cool so if you [followed these steps](https://pietropassarelli.gitbooks.io/subtitlecomposer-app/content/installing.html) then it might be this issue to do with the part to the python file? See link for more details https://github.com/sillsdev/aeneas-installer/issues/33 ?

**Comment by pietrop** [comment]
`cmd`+`alt`+`i` opens up the inspector console in the app, if you can upload a screenshot here when it gets stuck that’ll be helpfull to see if it is the same problem

**Comment by braincoded** [comment]
Thanks a lot for the quick reply! This is the error message that is logged in the console:

```
Uncaught Error: ENOENT: no such file or directory, open '/Users/sub1/Desktop/Sonnet.mp3.srt'
    at Object.fs.openSync (fs.js:652:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:508:29)
    at /Applications/subtitles-composer-app.app/Contents/Resources/app/src/renderer.js:176:20
    at /Applications/subtitles-composer-app.app/Contents/Resources/app/node_modules/subtitlescomposer/index.js:21:11
    at /Applications/subtitles-composer-app.app/Contents/Resources/app/node_modules/subtitlescomposer/aeneas_node/index.js:27:13
    at ChildProcess.exithandler (child_process.js:289:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)


fs.openSync | @ | fs.js:652
-- | -- | --
  | module.(anonymous function) | @ | ELECTRON_ASAR.js:172
  | fs.readFileSync | @ | fs.js:553
  | fs.readFileSync | @ | ELECTRON_ASAR.js:508
  | (anonymous) | @ | /Applications/subtitles-composer-app.app/Contents/Resources/app/src/renderer.js:176
  | (anonymous) | @ | /Applications/subtitles-composer-app.app/Contents/Resources/app/node_modules/subtitlescomposer/inde…:21
  | (anonymous) | @ | /Applications/subtitles-composer-app.app/Contents/Resources/app/node_modules/subtitlescomposer/aene…:27
  | exithandler | @ | child_process.js:289
  | emitTwo | @ | events.js:125
  | emit | @ | events.js:213
  | maybeClose | @ | internal/child_process.js:921
  | stream.socket.on | @ | internal/child_process.js:348
  | emitOne | @ | events.js:115
  | emit | @ | events.js:210
  | _handle.close | @ | net.js:549


```

**Comment by pietrop** [comment]
Yeah, thanks, seems like it.
What operating system are you on?

**Comment by braincoded** [comment]
I'm running High Sierra 10.13.6.

After trying to fix the Python installation via `brew` in numerous ways without any success I've found a workaround that helped: I created a symbolic link to the missing directory causing the error:

`ln -s /usr/local/bin/python /usr/local/opt/python/bin/python2.7`

This solved the issue for me at the moment.
Thanks again for sharing the great GUI for Aeneas with us!

**Comment by pietrop** [comment]
Awesome thanks @braincoded !

Glad you were able to use it, and thanks for sharing the workaround!

Going to share this symlink solution with a few other folks who had this problem while I see if there can be a more permanent solution

**Comment by pietrop** [comment]
Re-opening as others having same issue. and the `ln -s`  fix is not working for them

Possible quick fix, suggested by @bfasenfest

- installed brew (https://brew.sh/)
- installed python 2 using brew - `brew install python@2` (https://docs.python-guide.org/starting/install/osx/)
- copy symlink  `usr/local/opt/python2`
- and rename symlink to ` usr/local/opt/python`

---
However it be good to find a more solid solution of some sort.

**Comment by pietrop** [comment]
There's a new release of the Aeneas installer [sillsdev/aeneas-installer/releases](https://github.com/sillsdev/aeneas-installer/releases) for mac [aeneas tools Installer v1.7.3.0_2 updated for Python 3.7](https://github.com/sillsdev/aeneas-installer/releases/tag/v1.7.3.0_2) which seems to be fixing this issue so closing this for now. 

I tested it by installing `aeneas tools Installer v1.7.3.0_2 updated for Python 3.7` on a new mac using these latest releases and it worked without needed to tweak anything. But feel free to re-open if this shows up again.
